# Generated by Django 5.1.13 on 2025-12-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Enter your username', max_length=250, unique=True)),
                ('email', models.EmailField(max_length=450, unique=True)),
                ('age', models.IntegerField(choices=[('Minor', 'Below 18'), ('ADULT', '18 +'), ('SENIOUR', ' 65 +')])),
            ],
        ),
    ]
